### ISSUE TITLE
Change color theme and accent color

### ISSUE THREAD

**Issue by aaalveee** [tryswift/trySwiftAppFinal#15]

**Comment by aaalveee** [comment]
![simulator screen shot 20-feb-2017 8 12 45 pm](https://cloud.githubusercontent.com/assets/5159405/23122932/af99727e-f7a9-11e6-92fd-c20af4847d15.png)


Commit :  
https://github.com/tryswift/trySwiftAppFinal/commit/4f9ec21e90174135568bbb9c8b38a54ad089a95b

**Comment by BasThomas** [comment]
FYI, @aaalveee, you can put something like `fixes #15` in a commit description, and GitHub will automatically close the issue and link the commit. :)
