### ISSUE TITLE
Twitter handle names should link out to twitter

### ISSUE THREAD

**Issue by pivotal-misa-sakamoto** [tryswift/trySwiftAppFinal#27]
Due to the blue color treatment it looks like the twitter handle name is a tapapable item. It would be great if it can be opened in twitter

**Comment by pivotal-misa-sakamoto** [comment]
Clarification : the twitter handle name I'm talking about is not the "follow @..." one

**Comment by BasThomas** [comment]
Do you mean the ones below the speakers' bios? Those should open in your Twitter client (or Safari if none are installed)

**Comment by BasThomas** [comment]
Fixed by #51
